language: node_js
node_js:
- '6'
install:
- npm install
script:
- npm run package
deploy:
  provider: releases
  api_key:
    secure: y78mBMpmZA3LnrkK10TAZ8TFGYqEYo6D9R2gO53miON3r4hwDx2DBdsU0sV1YpDsVdZ/RBr/cHs8ej8N5LMqoK5ic07P6E2BAro3S1INs/CbHtgJsFb1jxAelzjQf8h4oRjz8hhLETaLydoxt0YnrscdOPsr4i7JJPQjU8to+XQt7vqtAR9jIq02O4h8i/6yC+iRzD0Oswjy3NeOCgO/tK+Y7YZ3rDWq0WOzHIrZ60aj16+CxdXRbL/kR45/LMaF9YEwj3gwM/um39vyUh8h3PyIdMb8IBWEE4cQi/zrPfA29rEFWeVSJS7ASRYfGVFvWqG4l+/P4N05JqzLJ4BabRWLc8KHs2uW/QudabUG+085t80FQKmGGByCBtkFbCUVx+hea7U6uZ5+GIcay+5eupYJdm6/vNJbsrq52znZr1CFP5o4ZhIwR4xeN4wFDAaCLl/guKgd9mDeYmqC1eUMMy62DqodX3rcj3s9RBmLVbpDLGbvZnNvu23Zz8wlCkl1Hi1yMMEZqQnFoFkYPu6pCqqiR2VFLgU7RYsXkRYGC67LgAuWLKc3Xt8AFRTK3LjHHlOQJTQ7TGk0aaxdvBcWisewtDY749Q3aYBf6EM4NUNlzdbPJpzxVncOwBYzU7paatFHKP0C20OMSjnNfpzUJTYL+sXdCv5PLS++vEnktWE=
  file: dist/app.zip
  skip_cleanup: true
  on:
    tags: true

