language: node_js
node_js:
- '6'
install:
- npm install
script:
- npm run package
deploy:
  provider: releases
  api_key:
    secure: VeZe1gG4BRd0hV8iMY0pMGij/aoJiYpBs0UJR65fsUoE9kFYbfDQKtkAFkGmWr4RLn33hg0TheryfY+tq8iKiB/ULEf0cjIjUcOOg05zZ9UlRviIsP+nSTp70Y2G9P4mBAa92kcT+ae1JJyKnGtKYeQ/tzz34z2pwbCkG+TV7QdF04jPEuj8ouPmmsRtdv1FQPAUJL0w8a8zGJVQtF0iZEVi1t+jxMLrow/M4VVmG1g1v9vJtff7ZZdtHe8SPZzjD0VZuHJ2pGAJudmoigrMcbt+1amUyIr6ZzH9b21KiCyDcDJTxSrCvHDzk95wJv64nOcCS3FpLc5vvbHx5tv3PHfZgbJzlvuBu9bwa69+xUHZ2x3W/FjLnGwo+W9i4+4a3JaUzDVJv6x3al8l6KslwVxn9MLo4AY5gKa7YSDcqdWz1p3APRd8t5EFHAirwByq4m9XIuulRxAhVKJxTMq7islxbGmvvYPYmbawPMFt1LMU2IM/hO/dBFRkqIDnYmC4QpvBd8hKKJGz1B18lxLd0+iNg3FMpse408YLoVn3jtTF+v0UgzVrvXd1lUg3gsN265C+4+lSy6F5QDLAl7X+nyFtjF46muEK2jfrBOaz1tvpDMo6d4PBbe2t/KTb2WFoeEGf/gKiyRei+mZzI6jqBxrxHolNEe/kQ6/M7NJPWnE=
  file: dist/app.zip
  skip_cleanup: true
  on:
    tags: true

