language: node_js
node_js:
- '6'
install:
- npm install
script:
- npm run package
deploy:
  provider: releases
  api_key:
    secure: m7MXOgFJaHU6LHrDvkpwDMUtXLMwg30EMK4BT282EXcWSpycvtcUHUYkFDmvUxIBeMSAJTIIivDCwNbTcB4vAxWUlRnsvckgJBGJe9PO8cBT7CxztiWcC6MNoVCne+bXNPicdPyPWpE5DcZxbC5CtS6ZtPhS63+zHmRTWSPztVGIz6Ok0DeX1uadWc9n8C0sb0FnSHzOajtcbn4XG6xL22WRzjEmToMHC+YaP5de/cbq0bNst2qZaehi6E9QlU+RCAfDK+AzSljSvVuY0H95zFNke/1BFxR/iZWV0Sm/noM7vM9Id2Zrp9Ws7x1KeieoMXnSkVCM9qiL3PJzEt94hTkJY0bdDayyfZzLWTyyogxSaHUNaBhkDaG5u4NFydCJWq5T70Isl4b7UdYiyZU2Qc7wW7A3E7C5KvsIogkj5Y4gjWeLuf14e4fKP/AUR18Z0K/+tFCr8sNTEmOHCov9Ud428ZzApOiUf4Ny0oXkYsvJuEVCGFmVL3+AVg+/INZER5q2Qrqoscg7KXXpbrhabgSJA3+a0FmePlVKQf+u8uKBaDcDjrFE0IiAplxhZAxLN3S4Zv34FSJF3AtuhtEqn8GIyoAH65s/5uYxUGnzildcEFhyLpZGeOrcrlNHpnzYecsPAUy+glwVzXpt+p95E7pyszHRXyVjVlXfWBQl1Ys=
  file: dist/app.zip
  skip_cleanup: true
  on:
    tags: true

